In [64]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [65]:
df = pd.read_csv("C:\\Users\ABC\\AppData\\Local\Temp\\Rar$DIa7068.41780\\Titanic-Dataset.csv")
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [66]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [68]:
df["Age"].fillna(df["Age"].mean(), inplace=True)

In [69]:
df.dropna(subset=["Fare"], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [70]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [71]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [72]:
df["Sex"]  = le.fit_transform(df["Sex"])
df["Ticket"]= le.fit_transform(df['Ticket'])
df["Embarked"]= le.fit_transform(df["Embarked"])
df["Name"]= le.fit_transform(df["Name"])
df["Cabin"]= le.fit_transform(df["Cabin"])

In [73]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22.0,1,0,523,7.2500,147,2
1,2,1,1,190,0,38.0,1,0,596,71.2833,81,0
2,3,1,3,353,0,26.0,0,0,669,7.9250,147,2
3,4,1,1,272,0,35.0,1,0,49,53.1000,55,2
4,5,0,3,15,1,35.0,0,0,472,8.0500,147,2

In [74]:
df = df.astype(int)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22,1,0,523,7,147,2
1,2,1,1,190,0,38,1,0,596,71,81,0
2,3,1,3,353,0,26,0,0,669,7,147,2
3,4,1,1,272,0,35,1,0,49,53,55,2
4,5,0,3,15,1,35,0,0,472,8,147,2

In [75]:
x = df.drop("Survived",axis=1)
y = df["Survived"]

In [76]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [77]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [78]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0])

In [79]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64

In [80]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [81]:
accuracy_score(y_test,y_pred)

0.7653631284916201

In [82]:
confusion_matrix(y_test,y_pred)

array([[89, 16],
       [26, 48]])

In [83]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.85      0.81       105
           1       0.75      0.65      0.70        74

    accuracy                           0.77       179
   macro avg       0.76      0.75      0.75       179
weighted avg       0.76      0.77      0.76       179

In [84]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22,1,0,523,7,147,2
1,2,1,1,190,0,38,1,0,596,71,81,0
2,3,1,3,353,0,26,0,0,669,7,147,2
3,4,1,1,272,0,35,1,0,49,53,55,2
4,5,0,3,15,1,35,0,0,472,8,147,2
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,548,1,27,0,0,101,13,147,2
887,888,1,1,303,0,19,0,0,14,30,30,2
888,889,0,3,413,0,29,1,2,675,23,147,2
889,890,1,1,81,1,26,0,0,8,30,60,0
890,891,0,3,220,1,32,0,0,466,7,147,1

In [85]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [86]:
x_train_scaler = scaler.fit_transform(x_train) 
x_test_scaler = scaler.fit_transform(x_test)

In [87]:
from sklearn.neighbors import KNeighborsClassifier

In [88]:
knn_model = KNeighborsClassifier(n_neighbors=  5)
knn_model.fit(x_train_scaler,y_train)

KNeighborsClassifier()

In [89]:
y_pred_knn =knn_model.predict(x_test_scaler)
accuracy_score(y_test,y_pred_knn)

0.7877094972067039

In [90]:
confusion_matrix(y_test,y_pred_knn)

array([[92, 13],
       [25, 49]])

In [91]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       105
           1       0.79      0.66      0.72        74

    accuracy                           0.79       179
   macro avg       0.79      0.77      0.77       179
weighted avg       0.79      0.79      0.78       179

In [92]:
from sklearn.naive_bayes import GaussianNB

In [93]:
model_NB = GaussianNB()

In [94]:
model_NB.fit(x_train,y_train)

GaussianNB()

In [95]:
y_pred_NB  =model_NB.predict(x_test)
y_pred_NB

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [96]:
accuracy_score(y_test,y_pred_NB)

0.8044692737430168

In [97]:
confusion_matrix(y_test,y_pred_NB)

array([[87, 18],
       [17, 57]])

In [98]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       105
           1       0.76      0.77      0.77        74

    accuracy                           0.80       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.80      0.80      0.80       179

In [99]:
from sklearn.tree import DecisionTreeClassifier

In [100]:
model_DT = DecisionTreeClassifier(random_state=42)
model_DT.fit(x_train_scaler,y_train)

DecisionTreeClassifier(random_state=42)

In [101]:
y_pred_DT = model_DT.predict(x_test_scaler)

In [102]:
y_pred_DT

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

In [103]:
accuracy_score(y_test,y_pred_DT)

0.7039106145251397

In [104]:
confusion_matrix(y_test, y_pred_DT)

array([[75, 30],
       [23, 51]])

In [105]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.77      0.71      0.74       105
           1       0.63      0.69      0.66        74

    accuracy                           0.70       179
   macro avg       0.70      0.70      0.70       179
weighted avg       0.71      0.70      0.71       179

In [106]:
from sklearn.svm import SVC

In [107]:
model_svm = SVC(kernel = "rbf" )

In [108]:
model_svm.fit(x_train_scaler, y_train)

SVC()

In [109]:
y_pred_svm = model_svm.predict(x_test_scaler)

In [110]:
accuracy_score(y_test,y_pred_svm)

0.8044692737430168

In [111]:
confusion_matrix(y_test, y_pred_svm)

array([[92, 13],
       [22, 52]])

In [112]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       105
           1       0.80      0.70      0.75        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [113]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22,1,0,523,7,147,2
1,2,1,1,190,0,38,1,0,596,71,81,0
2,3,1,3,353,0,26,0,0,669,7,147,2
3,4,1,1,272,0,35,1,0,49,53,55,2
4,5,0,3,15,1,35,0,0,472,8,147,2
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,548,1,27,0,0,101,13,147,2
887,888,1,1,303,0,19,0,0,14,30,30,2
888,889,0,3,413,0,29,1,2,675,23,147,2
889,890,1,1,81,1,26,0,0,8,30,60,0
890,891,0,3,220,1,32,0,0,466,7,147,1

In [116]:
x = df.drop('Survived', axis=1)
y = df['Survived']

In [117]:
from sklearn.model_selection import cross_val_score

In [121]:
scaler = StandardScaler()
x_scaler = scaler.fit_transform(x)

In [122]:
scores = cross_val_score(model_svm,x_scaler,y,cv = 5 ,scoring = 'accuracy')

In [123]:
print(scores)

[0.82122905 0.81460674 0.79775281 0.80337079 0.83146067]

In [125]:
print(scores.mean())

0.813684012303057