In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv('C:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DIa16820.49299\\cars.csv')
df.head()

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#df['Model'].nunique() #value_counts()
df['Variant']. nunique() #value_counts()

1064

OneHotEncodung

In [10]:
pd.get_dummies(df[['Model', 'Variant']])

,Model_3-Series,Model_458 Speciale,Model_458 Spider,Model_488 Gtb,Model_5-Series,Model_6-Series,Model_7-Series,Model_718,Model_812 Superfast,Model_911,...,Variant_Zxi,Variant_Zxi (O),Variant_Zxi (O) Ags,Variant_Zxi (Opt),Variant_Zxi Ags,Variant_Zxi Amt,Variant_Zxi Amt (O),Variant_Zxi At,Variant_Zxi Plus,Variant_Zxi Plus Amt
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1272,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1273,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1274,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1275,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

k-1 OneHotEncoding

In [11]:
pd.get_dummies(df, columns=['Model', 'Variant'], drop_first= True)

,Make,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,Engine_Location,Fuel_System,...,Variant_Zxi,Variant_Zxi (O),Variant_Zxi (O) Ags,Variant_Zxi (Opt),Variant_Zxi Ags,Variant_Zxi Amt,Variant_Zxi Amt (O),Variant_Zxi At,Variant_Zxi Plus,Variant_Zxi Plus Amt
0,Tata,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
1,Tata,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
2,Tata,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
3,Tata,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
4,Tata,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,Honda,"Rs. 13,02,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,"Front, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
1272,Honda,"Rs. 14,21,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,"Front, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
1273,Honda,"Rs. 14,31,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,"Front, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
1274,Honda,"Rs. 12,01,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,"Front, Transverse",Injection,...,False,False,False,False,False,False,False,False,False,False
1275,Mitsubishi,"Rs. 68,62,560",3200 cc,4.0,4.0,AWD (All Wheel Drive),In-line,BS IV,"Front, Longitudinal",Injection,...,False,False,False,False,False,False,False,False,False,False

OneHotencoding using sklearn

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=42)
x_train.head()

         Make          Model           Variant Ex-Showroom_Price
984       Kia         Seltos    Htx 1.5 Diesel     Rs. 14,14,000
415  Mahindra     Kuv100 Nxt  K2 6Str Cng Taxi      Rs. 5,42,913
780     Volvo            S60          Momentum     Rs. 38,50,500
919      Fiat  Linea Classic      1.3 Multijet      Rs. 7,51,203
96     Toyota     Etios Liva     Dual Tone Vxd      Rs. 7,56,700

In [22]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
x_train_new = ohe.fit_transform(x_train[['Model', 'Variant']]).toarray()
x_test_new = ohe.transform(x_test[['Model', 'Variant']]).toarray()

ValueError: Found unknown categories ['Mustang', 'Land Cruiser', 'Granturismo', 'Urus', 'John Cooper Works', 'S5', 'Lc 500H', 'Alturas G4', 'Mercedes-Benz E-Class Cabriolet', 'Portofino', 'Mercedes-Benz C-Class Cabriolet', 'Range Evoque Convertible'] in column 0 during transform