In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("C:\\Users\\ABC\\AppData\\Local\\Temp\\Rar$DIa6632.37351\\iris.csv")

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x= df.drop('species', axis = 1)
y = df["species"]

In [7]:
x_trai,  x_test, y_train, y_test  = train_test_split(x, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [10]:
model_knn.fit(x_trai,y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.score(x_test,y_test)

1.0

In [12]:
from sklearn.svm import SVC

In [13]:
model_svm = SVC(C = 10,kernel="linear",gamma= "auto")

In [14]:
model_svm.fit(x_trai,y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [15]:
model_svm.score(x_test,y_test)

1.0

In [16]:
# now lets use the grid search cv

In [17]:
from sklearn.model_selection import GridSearchCV

In [18]:
classifier = GridSearchCV((model_svm), {
    'C' : [1,10,20,30],
    'kernel' :['rdf','linear'],
},cv = 5,return_train_score = False)

In [19]:
classifier.fit(x,y)

c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
20 fits failed out of a total of 40.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'poly', 'precomputed', 'linear', 'sigmoid'} or a callable. Got 'rdf' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan 0.98              nan 0.97333333        nan 0.96666667
        nan 0.96      ]
  warnings.warn(

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rdf', 'linear']})

In [20]:
classifier.cv_results_

{'mean_fit_time': array([0.00288148, 0.013557  , 0.00311213, 0.01175604, 0.0033793 ,
        0.01018252, 0.00360746, 0.01049738]),
 'std_fit_time': array([0.00025372, 0.00172789, 0.00213635, 0.00359384, 0.00153145,
        0.00185342, 0.00219205, 0.00251423]),
 'mean_score_time': array([0.        , 0.01246471, 0.        , 0.00790763, 0.        ,
        0.0067956 , 0.        , 0.00861869]),
 'std_score_time': array([0.        , 0.0032172 , 0.        , 0.00216875, 0.        ,
        0.00140132, 0.        , 0.00208686]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rdf', 'linear', 'rdf', 'linear', 'rdf', 'linear',
                    'rdf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rdf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rdf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rdf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rdf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([       nan, 0.96666667,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ]),
 'split1_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1.]),
 'split2_test_score': array([       nan, 0.96666667,        nan, 0.9       ,        nan,
        0.9       ,        nan, 0.9       ]),
 'split3_test_score': array([       nan, 0.96666667,        nan, 0.96666667,        nan,
        0.93333333,        nan, 0.9       ]),
 'split4_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1.]),
 'mean_test_score': array([       nan, 0.98      ,        nan, 0.97333333,        nan,
        0.96666667,        nan, 0.96      ]),
 'std_test_score': array([       nan, 0.01632993,        nan, 0.03887301,        nan,
        0.0421637 ,        nan, 0.04898979]),
 'rank_test_score': array([5, 1, 5, 2, 5, 3, 5, 4], dtype=int32)}

In [21]:
results =pd.DataFrame(classifier.cv_results_)

In [22]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002881,0.000254,0.000000,0.000000,1,rdf,"{'C': 1, 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,0.013557,0.001728,0.012465,0.003217,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003112,0.002136,0.000000,0.000000,10,rdf,"{'C': 10, 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.011756,0.003594,0.007908,0.002169,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
4,0.003379,0.001531,0.000000,0.000000,20,rdf,"{'C': 20, 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.010183,0.001853,0.006796,0.001401,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3
6,0.003607,0.002192,0.000000,0.000000,30,rdf,"{'C': 30, 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
7,0.010497,0.002514,0.008619,0.002087,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4

In [23]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rdf              NaN
1        1       linear         0.980000
2       10          rdf              NaN
3       10       linear         0.973333
4       20          rdf              NaN
5       20       linear         0.966667
6       30          rdf              NaN
7       30       linear         0.960000

In [24]:
from sklearn.model_selection import RandomizedSearchCV

In [25]:
classifier_r = RandomizedSearchCV((model_svm), {
    'C' : [1,10,20,30],
     'kernel' :['rdf','linear'],
},n_iter=4,cv = 5,return_train_score = False)

In [26]:
classifier_r.fit(x,y)

c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
15 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'poly', 'precomputed', 'linear', 'sigmoid'} or a callable. Got 'rdf' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\ABC\.anaconda\ankit\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.97333333]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rdf', 'linear']})

In [27]:
results = pd.DataFrame(classifier_r.cv_results_)

In [28]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002750,0.000212,0.000000,0.000000,rdf,20,"{'kernel': 'rdf', 'C': 20}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1,0.003670,0.001635,0.000000,0.000000,rdf,1,"{'kernel': 'rdf', 'C': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,0.002403,0.000653,0.000000,0.000000,rdf,30,"{'kernel': 'rdf', 'C': 30}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,0.009197,0.000262,0.005649,0.000549,linear,10,"{'kernel': 'linear', 'C': 10}",1.0,1.0,0.9,0.966667,1.0,0.973333,0.038873,1

In [29]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20          rdf              NaN
1        1          rdf              NaN
2       30          rdf              NaN
3       10       linear         0.973333

ensemble

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm  import SVC
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [31]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [32]:
x= df.drop('species', axis = 1)
y = df["species"]

In [33]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size= 0.2,random_state=42, stratify=y_encoded)

In [35]:
base_learners = [
    ('df', DecisionTreeClassifier(random_state=42)),
    ('SVC', SVC(probability=True, kernel='rbf', random_state=42)),
    ('lr', LogisticRegression(max_iter=1000))
]

In [36]:
meta_learner = LogisticRegression(max_iter=1000)

In [37]:
meta_learner = LogisticRegression(max_iter=1000)

In [38]:
stacking_clf =StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_learner,
    cv= 5
)

In [39]:
stacking_clf.fit(x_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('df', DecisionTreeClassifier(random_state=42)),
                               ('SVC', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [40]:
y_pred = stacking_clf.predict(x_test)

In [41]:
accuracy = accuracy_score(y_test, y_pred)

In [42]:
accuracy

0.9666666666666667

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    
)

In [45]:
rf_model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [46]:
y_pred = rf_model.predict(x_test)

In [47]:
accuracy = accuracy_score(y_test, y_pred)

In [48]:
accuracy

0.9

In [49]:
from sklearn.ensemble import  AdaBoostClassifier,GradientBoostingClassifier

In [50]:
from xgboost import XGBClassifier

In [53]:
from xgboost import XGBClassifier

In [58]:
ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)

In [59]:
ada_model.fit(x_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [60]:
y_pred = ada_model.predict(x_test)

In [61]:
accuracy = accuracy_score(y_test, y_pred)

In [62]:
accuracy

0.9333333333333333

In [65]:
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

In [66]:
gb_model.fit(x_train, y_train)

GradientBoostingClassifier(random_state=42)

In [67]:
y_pred = gb_model.predict(x_test)

In [70]:
accuracy = accuracy_score(y_test,y_pred)

In [71]:
accuracy

0.9666666666666667

In [77]:
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1,max_depth=3,use_label_encoder=False, eval_metric='mlogloss', random_state=42)

In [80]:
xgb_model.fit(x_train, y_train)

c:\Users\ABC\.anaconda\ankit\Lib\site-packages\xgboost\training.py:200: UserWarning: [21:47:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [83]:
y_pred = gb_model.predict(x_test)

In [84]:
accuracy = accuracy_score(y_test,y_pred)

In [85]:
accuracy

0.9666666666666667

unsupervised